---
apiVersion: v1
kind: Service
metadata:
  name: zoo
  labels:
    app: zookeeper-1
spec:
  ports:
    - name: client
      port: 2181
      protocol: TCP
    - name: follower
      port: 2888
      protocol: TCP
    - name: leader
      port: 3888
      protocol: TCP
  selector:
    app: zookeeper-1
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-service
  labels:
    name: kafka
spec:
  ports:
    - port: 9092
      name: kafka-port
      protocol: TCP
  selector:
    app: kafka
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: zookeeper-deployment-1
spec:
  selector:
    matchLabels:
      app: zookeeper-1
  template:
    metadata:
      labels:
        app: zookeeper-1
    spec:
      containers:
        - name: zoo1
          image: confluentinc/cp-zookeeper
          ports:
            - containerPort: 2181
          env:
            - name: ALLOW_ANONYMOUS_LOGIN
              value: "yes"
            - name: ZOOKEEPER_CLIENT_PORT
              value: "2181"

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: kafka-broker0
spec:
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka
          image: confluentinc/cp-kafka
          ports:
            - containerPort: 9092
          env:
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: zoo:2181
            - name: KAFKA_BROKER_ID
              value: "1"
            - name: KAFKA_ADVERTISED_LISTENERS
              value: PLAINTEXT://kafka-service:9092
            - name: KAFKA_AUTO_CREATE_TOPICS_ENABLE
              value: "true"
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "1"


---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: kafka-cat
spec:
  selector:
    matchLabels:
      app: kafka-cat
  template:
    metadata:
      labels:
        app: kafka-cat
    spec:
      containers:
        - name: kafka-cat
          image: confluentinc/cp-kafkacat
          command: ["/bin/sh"]
          args: ["-c", "trap : TERM INT; sleep infinity & wait"]

---

apiVersion: v1
kind: Service
metadata:
  name: ocp-demo-app-kafka
  labels:
    app: ocp-demo-app-kafka
spec:
  type: NodePort
  selector:
    app: ocp-demo-app-kafka
  ports:
  - protocol: TCP
    port: 8080
    nodePort: 30080
    name: http
    
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ocp-demo-app-kafka
spec:
  selector:
    matchLabels:
      app: ocp-demo-app-kafka
  replicas: 1
  template:
    metadata:
      labels:
        app: ocp-demo-app-kafka
    spec:
      containers:
      - name: ocp-demo-app-kafka
        image: sumitgupta28/ocp-demo-app-kafka:latest
        ports:
        - containerPort: 8080
        env:
          - name: KAFKA_ENDPOINT
            value: kafka-service:9092
            

