apiVersion: apps/v1
kind: Deployment
metadata:
  name: example
  namespace: sumit-gupta-redhat-code
spec:
  selector:
    matchLabels:
      app: hello-openshift
  replicas: 3
  template:
    metadata:
      labels:
        app: hello-openshift
    spec:
      containers:
        - name: hello-openshift
          image: openshift/hello-openshift
          ports:
            - containerPort: 8080

            
---

apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: ocp-demo-app-db-build
  namespace: sumit-gupta-redhat-code
spec:
  source:
    git:
      uri: 'https://github.com/sumitgupta28/ocp-demo-app.git'
    type: Git
    contextDir: /ocp-demo-app-db
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: 'ruby:2.4'
        namespace: openshift
      env: []
  triggers:
    - type: ImageChange
      imageChange: {}
    - type: ConfigChange
            