spring:  
    
  datasource:
    url: jdbc:postgresql://postgresql:5432/sampledb

  jpa:
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    ddl-auto: create
    
