spring:  
    
  datasource:
    #url: jdbc:postgresql://${POSTGRESQL_SERVICE_NAME}:5432/${POSTGRESQL_DB_NAME}
    url: jdbc:postgresql://${POSTGRESQL_SERVICE_NAME}:${POSTGRESQL_PORT}/${POSTGRESQL_DB_NAME}
    password: ${POSTGRESQL_PASSWORD}
    username: ${POSTGRESQL_USER}

  jpa:
    properties:
      hibernate:
        format_sql: true
        generate-ddl: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    generate-ddl: true
    ddl-auto: create-drop 
    
