spring:  
    
  datasource:
    url: jdbc:postgresql://postgresql:5432/${POSTGRESQL_DB_NAME}
    password: ${POSTGRESQL_USER}
    username: ${POSTGRESQL_PASSWORD}

  jpa:
    properties:
      hibernate:
        format_sql: true
        generate-ddl: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    generate-ddl: true
    ddl-auto: create-drop 
    
