version: '3.3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper
    ports:
      - 2181:2181
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOOKEEPER_CLIENT_PORT=2181


  kafka:
    image: confluentinc/cp-kafka
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true
      
  postgresql:
    image: 'postgres:13.1-alpine' 
    container_name: postgresql
    environment:
     - POSTGRES_DB=sample_database
     - POSTGRES_USER=postgresql_user
     - POSTGRES_PASSWORD=postgresql_password
  
  ocp-demo-app-db-kafka:
    build: .
    container_name: ocp-demo-app-db-kafka
    ports:
      - 8080:8080
    depends_on:
      - postgresql
      - zookeeper
      - kafka

    environment:
      - POSTGRESQL_DB_NAME=sample_database
      - POSTGRESQL_USER=postgresql_user
      - POSTGRESQL_PASSWORD=postgresql_password
      - POSTGRESQL_PORT=5432
      - KAFKA_ENDPOINT=localhost:9092
