version: '3.3'
services:
  postgresql:
    image: 'postgres:13.1-alpine' 
    container_name: postgresql
    environment:
     - POSTGRES_DB=sample_database
     - POSTGRES_USER=postgresql_user
     - POSTGRES_PASSWORD=postgresql_password
  
  ocp-demo-app-db-kafka:
    build: .
    container_name: ocp-demo-app-db-kafka
    ports:
      - 8080:8080
    depends_on:
      - postgresql
    environment:
      - POSTGRESQL_DB_NAME=sample_database
      - POSTGRESQL_USER=postgresql_user
      - POSTGRESQL_PASSWORD=postgresql_password
      - POSTGRESQL_PORT=5432
