apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app-fly-way
spec:
  selector:
    matchLabels:
      app: demo-app-fly-way
  replicas: 3
  template:
    metadata:
      labels:
        app: demo-app-fly-way
    spec:
      initContainers:
      - name: init-db-service
        image: busybox:1.28
        command: ['sh', '-c', "until nslookup postgresql.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for postgresql; sleep 2; done"]
      containers:
      - name: demo-app-fly-way
        image: sumitgupta28/demo-app-fly-way:latest
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 30
          timeoutSeconds: 1        
        env:
          - name: POSTGRESQL_DB_NAME
            valueFrom: 
              configMapKeyRef:
                name: postgres-configuration
                key: POSTGRES_DB        
                
          - name: POSTGRESQL_USER
            valueFrom: 
              configMapKeyRef:
                name: postgres-configuration        
                key: POSTGRES_USER        
                
          - name: POSTGRESQL_PASSWORD
            valueFrom: 
              configMapKeyRef:
                name: postgres-configuration        
                key: POSTGRES_PASSWORD        
                
          - name: POSTGRESQL_SERVICE_NAME
            valueFrom: 
              configMapKeyRef:
                name: postgres-configuration        
                key: POSTGRESQL_SERVICE_NAME        

          - name: POSTGRESQL_PORT
            valueFrom: 
              configMapKeyRef:
                name: postgres-configuration        
                key: POSTGRESQL_PORT        
                
                
                
                