logging.level:
  org.springframework.boot.web: WARN
  org.springframework.boot.context: WARN
  org.springframework.web: WARN
  org.springframework.orm: WARN
  org.springframework.core: WARN
  org.springframework.jmx: WARN
  org.hibernate: WARN
  org.apache.catalina: WARN
  org.flywaydb: DEBUG

spring:  
  datasource:
    url: jdbc:postgresql://${POSTGRESQL_SERVICE_NAME}:${POSTGRESQL_PORT}/${POSTGRESQL_DB_NAME}
    password: ${POSTGRESQL_PASSWORD}
    username: ${POSTGRESQL_USER}
    hikari:
      schema: emp

  flyway:
    sql-migration-prefix: V
    schemas:
      - emp
    create-schemas: true
  jpa:
    show-sql: true
    database: postgresql
    generate-ddl: false
    hibernate:
      ddl-auto: none
            