version: '3.3'
services:
    jenkins:
        build: .
        restart: unless-stopped
        container_name: jenkins
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - /var/jenkins_home:/var/jenkins_home
            - $(which docker):/usr/bin/docker
        ports:
            - 8080:8080
