apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "demo-app-db-fly-way.fullname" . }}
  labels:
    {{- include "demo-app-db-fly-way.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "demo-app-db-fly-way.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "demo-app-db-fly-way.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "demo-app-db-fly-way.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          #livenessProbe:
            #initialDelaySeconds: 20
            #httpGet:
              #path: /
              #port: http
          #readinessProbe:
            #initialDelaySeconds: 20
            #httpGet:
              #path: /
              #port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: POSTGRESQL_USER
              value: {{ .Values.postgresql.postgresqlUsername }}
            - name: POSTGRESQL_PASSWORD
              value: {{ .Values.postgresql.postgresqlPassword }}
            - name: POSTGRESQL_DB_NAME
              value: {{ .Values.postgresql.postgresqlDatabase }}
            - name: POSTGRESQL_SERVICE_NAME
              value: {{ include "demo-app-db-fly-way.postgresql.service" . }}
            - name: POSTGRESQL_PORT
              value: "5432"
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
