kind: PersistentVolume
apiVersion: v1
metadata:
  name: {{ include "demo-app-db-fly-way.fullname" . }}-db-volume
  labels:
    type: local
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/db-data"